name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
# on:
#   push:
#     branches:
#       - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      # Wait for manual approval
      # - name: Wait for Approval
      #   if: github.ref == 'refs/heads/main'
      #   run: echo "Waiting for manual approval"
      #   timeout-minutes: 10080 # Set a large timeout, adjust as needed
  # Approve-Deployment:
  #   needs: Deploy-Production
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Approve Deployment
  #       if: github.actor == 'shruti89041' # Replace 'your-username' with your GitHub username
  #       run: echo "::set-output name=approved::true"
  #     - name: Check Approval
  #       run: exit ${{ job.previousRun.steps.Deploy-Production.outputs.approved }}

